### ISSUE TITLE
Unable to use Apion module from irb

### ISSUE THREAD

**Issue by dehesa** [coontail/Apion#2]
1. Install the ruby gem.
    I make sure of it by reviewing `gem list`, and see `apion (0.2.0)`.
2. Run the interactive ruby console.
    ```
    $ irb
    ```
3. Load the Apion module
    ```
    irb(main):001:0> require 'apion'
    => true
    ```
4. Try to use one of your examples:
    ```
    irb(main):002:0> Apion.apion("Le chat dodu et roux mange une quiche aux lardons")
    NameError: uninitialized constant Apion
        uninitialized constant Apion
        from (irb):2
        from /usr/bin/irb:/11:in `<main>`
    ```

PS: I am not a ruby developer. I am not sure whether I am missing something out.

**Comment by nicolrx** [comment]
Same problem here. What was your solution? It seems the Module isn't included. Thanks.

**Comment by dehesa** [comment]
I never managed! I just stopped using it altogether. It seems this library is completely abandoned 😔

**Comment by nicolrx** [comment]
I created a working version here: https://github.com/nicolrx/IPA-Phonetics

**Comment by dehesa** [comment]
Good stuff! I will check it out once I have a bit more time.

**Comment by nicolrx** [comment]
Feel free to contribute, this is the first gem I create!

**Comment by dehesa** [comment]
Sure, but to be honest French and Ruby are currently low in my priority list 🤷‍♂️
In any case, congrats for fixing this and pushing it out of the door.
